### ISSUE TITLE
Bugfix: Search Block being displayed for anonymous users

### ISSUE THREAD

**Issue by karanvp** [guptahemant/insta-clone#108]
**Requirement:-**
Search Block should only be shown to authenticated users and administrator.

**Reference:**
![Screenshot from 2022-03-31 15-10-57](https://user-images.githubusercontent.com/65488349/161026228-e316ed8b-5dcc-4012-b7f5-fe04304568d8.png)

**Testing:**
For anonymous user role , search block should be hidden.

**Comment by JayKandari** [comment]
Why no updates on this issue?
