### ISSUE TITLE
 Remove image when click on Remove current photo.

### ISSUE THREAD

**Issue by sharayu0** [guptahemant/insta-clone#111]
**Requirement :** 
Remove image when click on Remove current photo in Change Profile Photo Popup.

**Implementation :** 
1. Create a form with multiple submit button.
2. Set the function to each submit button.
3. Use Entity Api and the current user service to remove the photo for the current user.
4. Set the default image after removing the image.

**Testing :** 
1. Install the Instaform module.
2. Go to the route containing the edit profile form.
3. Click the link Change Profile photo, pop up will open.
4. Then click on Remove current photo and check if current image is removed or not.

**Comment by sharayu0** [comment]
1. Searching around the implementation of how to remove current image
2. searched around to create multiple submit buttons in a form using form API

**Comment by JayKandari** [comment]
PR Link : https://github.com/guptahemant/insta-clone/pull/114

**Comment by sharayu0** [comment]
Trying to add default image when user remove his profile photo.
Not find the appropriate way to do it, still working on it
