### ISSUE TITLE
Settings / Edit Profile Page

### ISSUE THREAD

**Issue by pritamyj** [guptahemant/insta-clone#12]
**Description** : Settings page displaying multiple links to different pages and its form

**Implementation** : Use 2 regions for Settings Links and Form
     
     1. The First region will contain 3 blocks - Settings links , Switch to Professional Account link and Account centre block.
     2. The Second region will display the content (Settings Form).
     3. Edit Profile Page will be displayed by default when clicked on Settings.
          - Create user info form for this page 
          - At the end add a link to 'Temporarily Disable your Account' page

**Testing** :

**Reference** : 
![Screenshot from 2021-12-09 20-39-34](https://user-images.githubusercontent.com/88623137/145422203-aa0772b1-e386-4fad-96a8-a6a5aa20e73a.png)

**Comment by sharayu0** [comment]
1. Created a basic edit profile page form with a form Api.
2. Use the "Current User" service to read all the data of the current logged in user and placed it in required field using default values.
3. and after editing this form updating the user's field values using Entity Api.
4. Added the multiple link tabs using Menu Api.
5. Styled the edit profile page with two parts of link tabs and edit profile form.
6. Created a Change profile photo link and created a pop-up when click on link.

**Comment by JayKandari** [comment]
What did you work on this ticket yesterday? why no updates here?
