### ISSUE TITLE
Change Password Page

### ISSUE THREAD

**Issue by pritamyj** [guptahemant/insta-clone#13]
**Description** : This page is for changing the password 

**Implementation** :  1. Create a form displaying Profile photo and Username at the top
                                  2. Add three fields - Old password, New password and Confirm password
                                  3. Add a link to Forgot password page

**Testing** :

**Reference** :
![Screenshot from 2021-12-09 21-00-32](https://user-images.githubusercontent.com/88623137/145426003-25030204-b5ed-4976-8a79-165c8cdd757c.png)

**Comment by sharayu0** [comment]
Searching around how to work on it and how to achieve this functionality. For structure, drupal have a form element for confirm password so we can use it here.

**Comment by sharayu0** [comment]
1.  Created a structure for  the change password form.
2. Also started working on the functionality of change password by first checking whether the user entered a correct current password and check whether it same as stored in the database as hashed.

**Comment by sharayu0** [comment]
1. Completed with the functionality tochange the password.
2. It check the current entered password with the hashed password stored in database, if it is same then it checks the new entered password and confirm password both must be same, if both are same it passes the condition and the new password will be stored in database.
