### ISSUE TITLE
Pop Up In feed page

### ISSUE THREAD

**Issue by atulghate** [guptahemant/insta-clone#18]
Description : By clicking on images in feed showing  pop up containing image with slide show  and comment list 

Implementation : Download pop up module and slide show module 

Testing :

Reference :
![pop up in feed](https://user-images.githubusercontent.com/88591747/145450959-b7bc968c-d973-4028-965c-b3fd7d6f29c3.png)

**Comment by JatinGupta40** [comment]
1. Explored Simple Popup Module. 
https://www.drupal.org/project/simple_popup_blocks
2. Tried Colorbox Module for pop-up
https://www.drupal.org/project/colorbox
To Install, Run on cmd - composer require 'drupal/colorbox:^1.8'

**Comment by JatinGupta40** [comment]
1. Need to add a pop-up for image/post.
2. Need to explore how to show the details like user name, comments, number of likes on the pop-up

**Comment by JatinGupta40** [comment]
1. Added class= "use-ajax", data-dialog-type="modal" using Drupal Behaviours(JS).
2. Added this because, when image/post is clicked, the custom modal can be executed to popup with a complete description of the post, like - likes on image, comments, add comments etc.

**Comment by JatinGupta40** [comment]
1. Completed Js for popup user posts.
2. Started working on its CSS, to show the image, likes, and comments. (As shown in the above Issue Description)

**Comment by VighneshSadagopal** [comment]
Created a view that would display a node image, authored information and flags in a popup modal.
Alter the existing view of user post display that would give the node information like the node id in the url.

**Remaining Tasks:**
1. Applying css to the modal as per the original instagram reference

**Comment by JatinGupta40** [comment]
1. Taken Pull
2. Applying CSS

**Comment by JatinGupta40** [comment]
1. Taken fresh Pull today again due to some issue
2. Applying CSS on my popup on user's

**Comment by JayKandari** [comment]
Can you make sure to add more details to your updates? the updates here is unwanted and not helping others understand.. @JatinGupta40

**Comment by JatinGupta40** [comment]
1. Added relevant fields like - image. user name, number of likes, and bookmark option to the popup modal.
2. Applied CSS to my popup modal to make it look better.
3. On the left side there is the user's uploaded image and on the right side, the user's name and number of like that post got is shown

**Comment by JayKandari** [comment]
@JatinGupta40 : The daily status on ticket is okay but still needs more improvementt. 

@sharayu0 : Can we close this if done?
