### ISSUE TITLE
Message Functionality 

### ISSUE THREAD

**Issue by sharayu0** [guptahemant/insta-clone#21]
**Description :** Create a Meassage Functionality

**Implementation :** Create a Message Functionality that User Can Send And Receive Private Message With a Single User and Also With a Groups Of Users Using a Private Message Module.

**Testing :**

**Reference :**
![Screenshot from 2021-12-10 00-39-51](https://user-images.githubusercontent.com/86892997/145460328-3b238146-074f-4b29-b818-9e1a2c9e1a55.png)

**Comment by JayKandari** [comment]
no updates about yesterday ?

**Comment by sharayu0** [comment]
Working around the message functionality using the private message , message notify module. Changing some configurations and settings for to send messages to the user. and also working around permissions for the user and the messages to send by the user.

**Comment by JayKandari** [comment]
@sharayu0 : can you update what all things are finished and what all things are pending on this ticket?

**Comment by sharayu0** [comment]
Changes some settings in private message thread, and private message manage display and added picture of the author to display it in private message thread.
