### ISSUE TITLE
Story Block

### ISSUE THREAD

**Issue by VighneshSadagopal** [guptahemant/insta-clone#29]
**Description :** This Block Will Display a content-type Of story that will be unpublished after 24 hours

**Implementation :**
1. Create a content type for story which can have multiple media fields
2. Create view of the content type that shows user picture and username of the respective story content
3. Use Slick carousal in the view for displaying story content type in a slider
4. Story content slider will be displayed in a popup
5. Show loading bar at the top of each story by using JS
6. Once story is viewed by current user then it will be placed at the end, this can be done by using flag
7. Story will be unpublished after 24 hours

**Testing :**

**References :**
Before clicking story:
![Screenshot from 2021-12-12 01-58-48](https://user-images.githubusercontent.com/87809169/145690730-39c90cf4-e1f4-49bf-af7f-cabdd9defcd0.png)
After clicking story:
![Screenshot from 2022-03-24 03-57-55](https://user-images.githubusercontent.com/88623137/159806606-6484445b-ebad-48cd-b21c-a786ac47800a.png)

**Comment by pritamyj** [comment]
1. Created a content type for story which can have multiple media fields
2. Created view of the content type that shows user picture and username of the respective story content
3. Used Slick carousal in the view for displaying story content type in a slider
4. Changed css of slick carousal to display story content in a popup
5. Fixed the transition and margin issue of slider

**Comment by JayKandari** [comment]
@pritamyj : Thanks for the updates... Also can you also push your WIP MR/PR. also if along with what all things were done, if you can mention things that are pending..

**Comment by pritamyj** [comment]
Worked on:
1. Fixed the user image issue on story
2. Worked on fixing transition issue of story content
3. Changed css of Story content

To be done:
1. Will create another issues for this , since it needs to add more functionality
  a. Once story is viewed by current user then it will be placed at the end, this can be done by using flag
  b. Story will be unpublished after 24 hours
2. Will create MR for story block

**Comment by JayKandari** [comment]
What did you work on this ticket yesterday? why no updates here?

**Comment by JayKandari** [comment]
BLOCKED

**Comment by VighneshSadagopal** [comment]
1 .Created a content type for story with image fields .
2. Created view of the content type that shows user picture and username of the respective story content
3. With the  Slick module added Slick carousal in the view for displaying story content type in a slider
4. added the view in the header section .
Things to do :
1. added the css for the the view and will make corrections in the div structure.

**Comment by VighneshSadagopal** [comment]
1. Tried showing Users picture and on click displaying the story content but git some issues as colorbox filter in view doesnot provide an option to change images .
2. can find a way to add carousel to the colorbox module.
Things Can do:
1. Create a carousel through javascript.

**Comment by VighneshSadagopal** [comment]
Created a different view displaying user picture and after clicking on that user picture to display all the stories of all users.
Styles the users block of story where all users image are displayed .
THINGS REMAINING:
Add a carousel to all story page 
Link the user image with his story on that stories page

**Comment by JayKandari** [comment]
no updates about yesterday ?

**Comment by VighneshSadagopal** [comment]
1.Created a view of all the stories  and displaying them in a carousel format using the slick module and slick library.
2. added styles to page as per referenced to the original instagram site.
3. create a block view to display users profile image on the frontpage which will afterwards be click and be opened in the story page.
4. Styled the block that is been displayed on the frontpage.
Things remaining:
1. willl work on the way to display story as per the respective user been clicked on the frontpage.
2. styling of the story page.

**Comment by VighneshSadagopal** [comment]
1. Tried adding slick index to the carousel page of this view.
2added initial slides to the javascript file
Things to do
1. Generate a query in such a way that the url will display the I'd of the slick index.
2 find a way to pass views from user click to page.

**Comment by VighneshSadagopal** [comment]
1. Managed the slic carousel initial slide on the basis of slick index.
2. added a view result counter in the view and tried passimg it in the url for the next page that is story page.
3. then on the story page tried calling the url in javascript and then storing it in a variable and just getting out the no. through it and setting that particular no as initial slide.
4. Since the current class was only getting added to the first slide added a new class for the slides to show the active one.
Things remaining :
1. Styling the slick properly 
2. highlighting the centered slick.
