### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by VighneshSadagopal** [guptahemant/insta-clone#3]
**Description** : A Signup Page With Signup Form And Footer.

**Implementation** : Use 2 regions for Signup Form And Footer
1. The First region will contain 3 blocks Signup form , have an account , Get the app.
2. the Second region of Footer will Contain 3 Blocks With Links , Language Switcher And Copyright.

**Testing** : 

**Reference** :
![Screenshot from 2021-12-08 00-59-01](https://user-images.githubusercontent.com/87809169/145094037-7ab32b4a-eca1-4b98-9a89-1a57d0d5ee99.png)

**Comment by JayKandari** [comment]
Did you start working on this ticket yet ?

**Comment by JayKandari** [comment]
@karanvp : Please add an update on this ticket. what you did so far since last working day.

**Comment by karanvp** [comment]
researched on multistep forms . will continue work on this.

**Comment by karanvp** [comment]
Updates: 

- worked on creating custom signup form's styling part. 

Pending:

- fixing parts of styling.
- working on creating users.

**Comment by karanvp** [comment]
Raised PR for this issue. Will verify if everything is fine after testing.

**Comment by VighneshSadagopal** [comment]
Tested and Merged
