### ISSUE TITLE
Search form when user search autocomplete should have username fullname and user profile

### ISSUE THREAD

**Issue by VighneshSadagopal** [guptahemant/insta-clone#42]
**Description :** When someone uses the searchform and a particular user is searched the user's profile page should be shown.

**Implementation :** Implement this by using search api module which will allow to create a index that will redirect to a page that will show searched user's information

**Testing :**

**Comment by sharayu0** [comment]
Search autocomplete not displaying the users output properly.
Integrate with views.

**Comment by JatinGupta40** [comment]
1. Created view to show all the users, who have matching names as the user is entered in the search field.

**Comment by JatinGupta40** [comment]
1. Added SearchAPI Autocomplete Module, work on it.
2. Solved some issues related to SearchAPI Autocomplete.

**Comment by JayKandari** [comment]
What all things are pending on this ticket... can we also write this in our daily updates on the ticket ?

**Comment by JayKandari** [comment]
@JatinGupta40  : can you pls provide your updates... what you did on this ticket since last working day.

**Comment by JatinGupta40** [comment]
@JayKandari Sure.

**Comment by JatinGupta40** [comment]
## 15th April 2022
1. Research on how to show only those users whose name's characters/words are similar to what other users are searching for.
2. Autocomplete Module is working fine but showing all the user's name no matter what is being searched.

**Comment by JatinGupta40** [comment]
## 18-April-2022
1. At first, getting all the users in my autocomplete when searching any particular user
2. Worked and solved, showing the respected user when searching for a particular user. Also when typing the prefix(3 characters or less) of the name, only the user having the prefix is shown in the autocomplete of the search field.
3. Started adding CSS to the user's autocomplete.

**Comment by JatinGupta40** [comment]
## 19-Apr-2022

1. Research and Tried adding user profile images of the users that are being suggested by the Search API autocomplete.
2. Added Preprocess function for the user's image, still need to complete it.

**Comment by JatinGupta40** [comment]
1. Added preprocess function for the searched user's image.
2. Override the search_api_autocomplete_suggestion to add the image we fetched by the user's id using preprocess function. 
3. Added CSS to beautify the searched result i.e. - user's image and name.
