### ISSUE TITLE
Display numbers of likes and counts on user post when hover on image 

### ISSUE THREAD

**Issue by atulghate** [guptahemant/insta-clone#56]
Description : Display numbers of likes and comments when user hover on image

Implementation : 
To Do: added extra field  flag for likes and comments counts in user_post view  and styled them

**Comment by JayKandari** [comment]
What did you work on this ticket yesterday? why no updates here?

**Comment by atulghate** [comment]
1 had to reworked on that issue because of some conflic while rebase

**Comment by JayKandari** [comment]
what you did yesterday on this ticket?

**Comment by atulghate** [comment]
closed the old PR for this issue and created a new one for the same and sloved some styling issue with css  ~ https://github.com/guptahemant/insta-clone/pull/113

**Comment by JayKandari** [comment]
What you did yesterday on this ticket @atulghate ?

**Comment by atulghate** [comment]
yesterday i just connected with jatin discussed and checked  whether this PR work properly or not

**Comment by JayKandari** [comment]
Can we close this ticket if done?
