### ISSUE TITLE
Resolution error

### ISSUE THREAD

**Issue by karanvp** [guptahemant/insta-clone#75]
Incorrect Resolution taken while styling css if linux dock is enabled.

Total resolution is 1366px. If dock is not hidden , resolution considered while styling will be 1366px - dock size.

Solution:
To fix , must hide dock and then maximise screen to get correct resolution.

ERROR:
![Screenshot from 2022-02-14 10-10-33](https://user-images.githubusercontent.com/65488349/153801146-7ecb248e-1f7f-477f-bb8c-2d0d0f33b454.png)

**Comment by VighneshSadagopal** [comment]
![Screenshot from 2022-02-14 18-47-38](https://user-images.githubusercontent.com/87809169/153872472-f41ca4bb-8558-4d72-b1db-3a5e36e136c8.png)
The position of the slider of images and the show button which arises when you enter a character in the password input field should be changed.
