### ISSUE TITLE
Create a suggested-users slider block for users page

### ISSUE THREAD

**Issue by pritamyj** [guptahemant/insta-clone#86]
**Description** : A block which shows list of suggested users in a slider.

**Implementation** : Create a block view to list suggested users to follow or remove them from suggested-users-list and use slick slider. This block will be visible on any random user's user page (except current logged-in user).

**Testing** :

**References** :
![Screenshot from 2022-02-22 16-22-20](https://user-images.githubusercontent.com/88623137/155117797-b38f47d2-b2e2-48e8-acb9-cb9953182213.png)

**Comment by JayKandari** [comment]
The PR for this issue is pending since a long time.. What is the updates?
