### ISSUE TITLE
Implementing Infinite Scroll

### ISSUE THREAD

**Issue by vishalbandre** [guptahemant/insta-clone#93]
### Implementation Steps:
1. Adding [Views Infinite Scroll](https://www.drupal.org/project/views_infinite_scroll) with composer.
2. Configuring homepage feed view to use infinite scroll functionality.

**Before Infinite Scroll:**
i) The pagination provided by Full pager for the views was being shown.
![infinite-scroll-before](https://user-images.githubusercontent.com/2410377/160779754-44cba2ea-1782-49be-8db2-2223c379a286.png)

**After infinite scroll implementation:**
i) After implementing infinite scroll the pagination will not be shown.
ii) As per current configuration 2 posts will get loaded on each scroll.
iii) In this issue infinite scroll has been applied on "Flag Followers Content" view.

**How to test?**
i) The module is configured to load content on homepage infinitely.
ii) Before starting with testing you will need to have ample number of posts to observe the change. So, add at least 10+ posts so on each load at least 2 posts would be sufficient.
iii) To test it load the homepage of insta-clone.
iv) Browse the homepage posts normal way as you scroll up.
v) You would notice the existing full pagination should be gone.
vi) You would observe that the posts are being loaded infinitely. Two posts at a time.

**Comment by JayKandari** [comment]
Please groom this ticket more..

**Comment by JayKandari** [comment]
Why no updates here ?

**Comment by JayKandari** [comment]
Why no updates here for yesterday?

**Comment by JayKandari** [comment]
Again no status updates here for this issue? 
Can you please all make sure you put your status on each of the tickets you are working !
@vishalbandre @sharayu0 @atulghate @JatinGupta40 @VighneshSadagopal @pritamyj @karanvp

**Comment by vishalbandre** [comment]
The Infinite scroll implementation has been completed.
Raised a PR for review. https://github.com/guptahemant/insta-clone/pull/103

**Comment by VighneshSadagopal** [comment]
Tested reviewed and merged
